service: serverless-base # NOTE: update this with your service name

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev


functions:
  hello:
    handler: handler.helloLambda
